from sqlalchemy import create_engine
from dotenv import load_dotenv
import os

load_dotenv()

DATABASE_URL = (
    f"postgresql://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}@{os.getenv('DB_HOST')}/{os.getenv('DB_NAME')}"
)

# can u explain the parameters of create_engine?
# - pool_pre_ping: This parameter is used to check the connection before using it from the pool. It helps to avoid using stale connections.
# - pool_size: This parameter sets the number of connections to keep in the pool. In
#   this case, it is set to 10, which means that the pool will maintain up to 10 connections.
# - max_overflow: This parameter sets the number of connections that can be created beyond the pool_size. In this case, it is set to 20, which means that if all 10 connections in the pool are in use, up to 20 additional connections can be created on demand.
# - echo: This parameter is used to enable or disable the logging of SQL statements. When set to True, it will log all the SQL statements generated by SQLAlchemy. In this case, it is set to False, which means that SQL statements will not be logged.
engine = create_engine(DATABASE_URL, pool_pre_ping=True, pool_size=10, max_overflow=20, echo=True)
